language: julia

julia:
  - 1.5
  - 1
os:
  - linux
  - osx
  - windows

notifications:
  email:
    - Jie.Kang@agresearch.co.nz

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage");cd(Pkg.dir("SimGBS")); using Coverage; Codecov.submit(Codecov.process_folder())'
