name = "simGBS"
uuid = "92ef5d18-3a1f-4c68-9409-006e7edfe355"
authors = ["jie.kang@agresearch.co.nz <jie.kang@agresearch.co.nz> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
